<?php

namespace ContainerMlAfQpi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwitterConnectorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DDD\Twitter\Infrastructure\TwitterConnector' shared autowired service.
     *
     * @return \App\DDD\Twitter\Infrastructure\TwitterConnector
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/DDD/Twitter/Domain/SiteConnectorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DDD/Twitter/Infrastructure/TwitterConnector.php';

        return $container->privates['App\\DDD\\Twitter\\Infrastructure\\TwitterConnector'] = new \App\DDD\Twitter\Infrastructure\TwitterConnector($container->getEnv('string:TWITTER_CONSUMER_KEY'), $container->getEnv('string:TWITTER_CONSUMER_SECRET'), $container->getEnv('string:TWITTER_ACCESS_TOKEN'), $container->getEnv('string:TWITTER_ACCESS_TOKEN_SECRET'));
    }
}
