---
version: "3"

services:

  # --- MariaDB 10.5
  db:
    container_name: "twitter-bot-project-db"
    image: bitnami/mariadb:10.5
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=database
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - project-db:/bitnami:delegated

  # --- PHP 7.4
  php:
    container_name: "twitter-bot-project-php"
    image: bitnami/php-fpm:8.0
    depends_on:
      - db
      - redis
    volumes:
      - .:/app:delegated
      - ./docker/php.ini:/opt/bitnami/php/etc/conf.d/php.ini:ro

  # --- nginx 1.19
  nginx:
    container_name: "twitter-bot-project-nginx"
    image: bitnami/nginx:1.19
    ports:
      - "80:8080"
    depends_on:
      - php
    volumes:
      - .:/app:delegated
      - ./docker/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/site.conf:ro

  # --- Redis 6.0
  redis:
    container_name: "twitter-bot-project-redis"
    image: bitnami/redis:6.0
    environment:
      - REDIS_PASSWORD=redis

  # --- Elasticsearch 7.4.0 | Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  project-db:
    driver: local
  elasticsearch-data:
    driver: local
