<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQTOHpSW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQTOHpSW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQTOHpSW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQTOHpSW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQTOHpSW\App_KernelDevDebugContainer([
    'container.build_hash' => 'QTOHpSW',
    'container.build_id' => '96033105',
    'container.build_time' => 1657304071,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQTOHpSW');
